 services:
     - type: web
       name: chillonrails  # Replace with your desired service name
       runtime: ruby
       plan: free  # Or a paid plan for more resources
       buildCommand: "./bin/render-build.sh"
       startCommand: "bundle exec rails server"
       envVars:
         - key: RAILS_MASTER_KEY
           sync: false # Set to true if you want to sync the value from the dashboard.
         - key: DATABASE_URL
           fromDatabase:
             name: chillfiltr:us-west1:chillonrails-prod # Replace with your database service name
             property: connectionString